spring:
  mail:
    host: smtp.gmail.com
    username: shambillings06@gmail.com
    password: mbymnzzprfxinfjz
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
